config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/numpy/numpy:
      branch: main
      repo: https://github.com/numpy/numpy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/numpy/numpy git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-indigo-dragon.sh
        container: qc.acc_thirsty-corn-harrier
  QC.Doc:
    repos:
      github.com/numpy/numpy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-heliotrope-chin.sh
        container: qc.doc_slaphappy-violet-snail
      github.com/numpy/numpy git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-jade-dhole.sh
        container: qc.doc_sunny-orchid-orangutan
      github.com/numpy/numpy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-silver-chipmunk.sh
        container: qc.doc_woolly-buff-spider
      github.com/numpy/numpy restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-xanthic-zebra.sh
        container: qc.doc_shaggy-cardinal-booby
  QC.Lic:
    repos:
      github.com/numpy/numpy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-gamboge-binturong.sh
        container: qc.lic_snippy-ruby-booby
  QC.Sec:
    repos:
      github.com/numpy/numpy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-malachite-beaver.sh
        container: qc.sec_wiggy-thistle-chamois
  QC.Sty:
    repos:
      github.com/numpy/numpy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magenta-deer.sh
        container: qc.sty_nippy-gamboge-wrasse
      github.com/numpy/numpy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-aqua-echidna.sh
        container: qc.sty_slaphappy-asparagus-wolfhound
  QC.Ver:
    repos:
      github.com/numpy/numpy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tangerine-snake.sh
        container: qc.ver_greasy-sangria-toad
timeout: 5400
